apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: small-room-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: frontend.small-room.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80