apiVersion: v1
kind: Service
metadata:
	name: frontend
spec:
	type: LoadBalancer
	selector:
		app: small-room
		tier: frontend
	ports:
		- name: http
			port: 80
			targetPort: http
---
apiVersion: v1
metadata:
	name: backend
spec:
	type: ClusterIP
	selector:
		app: small-room
		tier: backend
	ports:
		- name: http
			port: 3000
			targetPort: http
---
apiVersion: v1
metadata:
	name: database
spec:
	type: ClusterIP
	selector:
		app: small-room
		tier: database
	ports:
		- name: postgres
			port: 5432
			targetPort: postgres
